package com.module.service;

import com.module.pojo.Kstock;

import java.util.List;

/**
 * Created by lenovo on 2017/6/10.
 */
public interface KstockService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kstock
     *
     * @mbggenerated
     */
    int deleteByCode(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kstock
     *
     * @mbggenerated
     */
    int insert(Kstock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kstock
     *
     * @mbggenerated
     */
    List<Kstock> selectByCode(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kstock
     *
     * @mbggenerated
     */
    int update(Kstock record);
}
