package com.module.pojo;

/**
 * Created by NJU on 2017/6/10.
 */
public class Echartskstock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.code
     *
     * @mbggenerated
     */

    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.open
     *
     * @mbggenerated
     */
    private int open;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.high
     *
     * @mbggenerated
     */
    private int high;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.close
     *
     * @mbggenerated
     */
    private int close;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.low
     *
     * @mbggenerated
     */
    private int low;

    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.code
     *
     * @param code the value for kstock.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.date
     *
     * @return the value of kstock.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.date
     *
     * @param date the value for kstock.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.open
     *
     * @return the value of kstock.open
     *
     * @mbggenerated
     */
    public int getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.open
     *
     * @param open the value for kstock.open
     *
     * @mbggenerated
     */
    public void setOpen(int open) {
        this.open = open ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.high
     *
     * @return the value of kstock.high
     *
     * @mbggenerated
     */
    public int getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.high
     *
     * @param high the value for kstock.high
     *
     * @mbggenerated
     */
    public void setHigh(int high) {
        this.high = high ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.close
     *
     * @return the value of kstock.close
     *
     * @mbggenerated
     */
    public int getClose() {
        return close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.close
     *
     * @param close the value for kstock.close
     *
     * @mbggenerated
     */
    public void setClose(int close) {
        this.close = close ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.low
     *
     * @return the value of kstock.low
     *
     * @mbggenerated
     */
    public int getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.low
     *
     * @param low the value for kstock.low
     *
     * @mbggenerated
     */
    public void setLow(int low) {
        this.low = low ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.volume
     *
     * @return the value of kstock.volume
     *
     * @mbggenerated
     */

    public Echartskstock(String code,String date,int open,int close,int low,int high){
    this.setCode(code);
    this.setDate(date);
    this.setOpen(open);
    this.setClose(close);
    this.setLow(low);
    this.setHigh(high);
    }
}
