package com.module.pojo;

public class Kstock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.open
     *
     * @mbggenerated
     */
    private String open;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.high
     *
     * @mbggenerated
     */
    private String high;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.close
     *
     * @mbggenerated
     */
    private String close;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.low
     *
     * @mbggenerated
     */
    private String low;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.volume
     *
     * @mbggenerated
     */
    private String volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.price_change
     *
     * @mbggenerated
     */
    private String priceChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.p_change
     *
     * @mbggenerated
     */
    private String pChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.ma5
     *
     * @mbggenerated
     */
    private String ma5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.ma10
     *
     * @mbggenerated
     */
    private String ma10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.ma20
     *
     * @mbggenerated
     */
    private String ma20;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.v_ma5
     *
     * @mbggenerated
     */
    private String vMa5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.v_ma10
     *
     * @mbggenerated
     */
    private String vMa10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.v_ma20
     *
     * @mbggenerated
     */
    private String vMa20;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.turnover
     *
     * @mbggenerated
     */
    private String turnover;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.code
     *
     * @return the value of kstock.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.code
     *
     * @param code the value for kstock.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.date
     *
     * @return the value of kstock.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.date
     *
     * @param date the value for kstock.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.open
     *
     * @return the value of kstock.open
     *
     * @mbggenerated
     */
    public String getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.open
     *
     * @param open the value for kstock.open
     *
     * @mbggenerated
     */
    public void setOpen(String open) {
        this.open = open == null ? null : open.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.high
     *
     * @return the value of kstock.high
     *
     * @mbggenerated
     */
    public String getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.high
     *
     * @param high the value for kstock.high
     *
     * @mbggenerated
     */
    public void setHigh(String high) {
        this.high = high == null ? null : high.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.close
     *
     * @return the value of kstock.close
     *
     * @mbggenerated
     */
    public String getClose() {
        return close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.close
     *
     * @param close the value for kstock.close
     *
     * @mbggenerated
     */
    public void setClose(String close) {
        this.close = close == null ? null : close.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.low
     *
     * @return the value of kstock.low
     *
     * @mbggenerated
     */
    public String getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.low
     *
     * @param low the value for kstock.low
     *
     * @mbggenerated
     */
    public void setLow(String low) {
        this.low = low == null ? null : low.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.volume
     *
     * @return the value of kstock.volume
     *
     * @mbggenerated
     */
    public String getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.volume
     *
     * @param volume the value for kstock.volume
     *
     * @mbggenerated
     */
    public void setVolume(String volume) {
        this.volume = volume == null ? null : volume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.price_change
     *
     * @return the value of kstock.price_change
     *
     * @mbggenerated
     */
    public String getPriceChange() {
        return priceChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.price_change
     *
     * @param priceChange the value for kstock.price_change
     *
     * @mbggenerated
     */
    public void setPriceChange(String priceChange) {
        this.priceChange = priceChange == null ? null : priceChange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.p_change
     *
     * @return the value of kstock.p_change
     *
     * @mbggenerated
     */
    public String getpChange() {
        return pChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.p_change
     *
     * @param pChange the value for kstock.p_change
     *
     * @mbggenerated
     */
    public void setpChange(String pChange) {
        this.pChange = pChange == null ? null : pChange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.ma5
     *
     * @return the value of kstock.ma5
     *
     * @mbggenerated
     */
    public String getMa5() {
        return ma5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.ma5
     *
     * @param ma5 the value for kstock.ma5
     *
     * @mbggenerated
     */
    public void setMa5(String ma5) {
        this.ma5 = ma5 == null ? null : ma5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.ma10
     *
     * @return the value of kstock.ma10
     *
     * @mbggenerated
     */
    public String getMa10() {
        return ma10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.ma10
     *
     * @param ma10 the value for kstock.ma10
     *
     * @mbggenerated
     */
    public void setMa10(String ma10) {
        this.ma10 = ma10 == null ? null : ma10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.ma20
     *
     * @return the value of kstock.ma20
     *
     * @mbggenerated
     */
    public String getMa20() {
        return ma20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.ma20
     *
     * @param ma20 the value for kstock.ma20
     *
     * @mbggenerated
     */
    public void setMa20(String ma20) {
        this.ma20 = ma20 == null ? null : ma20.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.v_ma5
     *
     * @return the value of kstock.v_ma5
     *
     * @mbggenerated
     */
    public String getvMa5() {
        return vMa5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.v_ma5
     *
     * @param vMa5 the value for kstock.v_ma5
     *
     * @mbggenerated
     */
    public void setvMa5(String vMa5) {
        this.vMa5 = vMa5 == null ? null : vMa5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.v_ma10
     *
     * @return the value of kstock.v_ma10
     *
     * @mbggenerated
     */
    public String getvMa10() {
        return vMa10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.v_ma10
     *
     * @param vMa10 the value for kstock.v_ma10
     *
     * @mbggenerated
     */
    public void setvMa10(String vMa10) {
        this.vMa10 = vMa10 == null ? null : vMa10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.v_ma20
     *
     * @return the value of kstock.v_ma20
     *
     * @mbggenerated
     */
    public String getvMa20() {
        return vMa20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.v_ma20
     *
     * @param vMa20 the value for kstock.v_ma20
     *
     * @mbggenerated
     */
    public void setvMa20(String vMa20) {
        this.vMa20 = vMa20 == null ? null : vMa20.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.turnover
     *
     * @return the value of kstock.turnover
     *
     * @mbggenerated
     */
    public String getTurnover() {
        return turnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.turnover
     *
     * @param turnover the value for kstock.turnover
     *
     * @mbggenerated
     */
    public void setTurnover(String turnover) {
        this.turnover = turnover == null ? null : turnover.trim();
    }
}