package com.module.pojo;

public class Kstock {

    private int id;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    private double MA5;

    private double MA10;

    private double MA20;

    private double MA30;

    private double BIAS;

    private double KDJ_K;

    private double KDJ_D;

    private double KDJ_J;

    private double WR;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.open
     *
     * @mbggenerated
     */
    private String open;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.high
     *
     * @mbggenerated
     */
    private String high;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.close
     *
     * @mbggenerated
     */
    private String close;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.low
     *
     * @mbggenerated
     */
    private String low;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kstock.volume
     *
     * @mbggenerated
     */
    private String volume;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.code
     *
     * @return the value of kstock.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.code
     *
     * @param code the value for kstock.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.date
     *
     * @return the value of kstock.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.date
     *
     * @param date the value for kstock.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.open
     *
     * @return the value of kstock.open
     *
     * @mbggenerated
     */
    public String getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.open
     *
     * @param open the value for kstock.open
     *
     * @mbggenerated
     */
    public void setOpen(String open) {
        this.open = open == null ? null : open.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.high
     *
     * @return the value of kstock.high
     *
     * @mbggenerated
     */
    public String getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.high
     *
     * @param high the value for kstock.high
     *
     * @mbggenerated
     */
    public void setHigh(String high) {
        this.high = high == null ? null : high.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.close
     *
     * @return the value of kstock.close
     *
     * @mbggenerated
     */
    public String getClose() {
        return close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.close
     *
     * @param close the value for kstock.close
     *
     * @mbggenerated
     */
    public void setClose(String close) {
        this.close = close == null ? null : close.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.low
     *
     * @return the value of kstock.low
     *
     * @mbggenerated
     */
    public String getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.low
     *
     * @param low the value for kstock.low
     *
     * @mbggenerated
     */
    public void setLow(String low) {
        this.low = low == null ? null : low.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kstock.volume
     *
     * @return the value of kstock.volume
     *
     * @mbggenerated
     */
    public String getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kstock.volume
     *
     * @param volume the value for kstock.volume
     *
     * @mbggenerated
     */
    public void setVolume(String volume) {
        this.volume = volume == null ? null : volume.trim();
    }

    public double getMA5() {
        return MA5;
    }

    public void setMA5(double MA5) {
        this.MA5 = MA5;
    }

    public double getMA10() {
        return MA10;
    }

    public void setMA10(double MA10) {
        this.MA10 = MA10;
    }

    public double getMA20() {
        return MA20;
    }

    public void setMA20(double MA20) {
        this.MA20 = MA20;
    }

    public double getMA30() {
        return MA30;
    }

    public void setMA30(double MA30) {
        this.MA30 = MA30;
    }

    public double getBIAS() {
        return BIAS;
    }

    public void setBIAS(double BIAS) {
        this.BIAS = BIAS;
    }

    public double getKDJ_K() {
        return KDJ_K;
    }

    public void setKDJ_K(double KDJ_K) {
        this.KDJ_K = KDJ_K;
    }

    public double getKDJ_D() {
        return KDJ_D;
    }

    public void setKDJ_D(double KDJ_D) {
        this.KDJ_D = KDJ_D;
    }

    public double getKDJ_J() {
        return KDJ_J;
    }

    public void setKDJ_J(double KDJ_J) {
        this.KDJ_J = KDJ_J;
    }

    public double getWR() {
        return WR;
    }

    public void setWR(double WR) {
        this.WR = WR;
    }
}