package com.module.mapper;

import com.module.pojo.Kstock;

public interface KstockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kstock
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kstock
     *
     * @mbggenerated
     */
    int insert(Kstock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kstock
     *
     * @mbggenerated
     */
    int insertSelective(Kstock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kstock
     *
     * @mbggenerated
     */
    Kstock selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kstock
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Kstock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kstock
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Kstock record);
}