package com.module.mapper;

import com.module.pojo.Kstock;

import java.util.List;

public interface KstockMapper {

    List<Kstock> selectByCode(String code);

    int deleteByCode(String code);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kstock
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kstock
     *
     * @mbggenerated
     */
    int insert(Kstock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kstock
     *
     * @mbggenerated
     */
    int insertSelective(Kstock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kstock
     *
     * @mbggenerated
     */
    Kstock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kstock
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Kstock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kstock
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Kstock record);
}